### ISSUE TITLE
eclipse+jdk1.8 项目没看到什么错误，但是Run As Java Application报出如下错误，哪位帮忙看下 谢谢

### ISSUE THREAD

**Issue by cavancao** [iBase4J/iBase4J-SpringBoot#1]
2018-03-29 11:25:57.815 [main] ERROR [SpringApplication:833] - Application run failed
java.lang.RuntimeException: 解密错误，错误信息：
	at top.ibase4j.core.util.SecurityUtil.decryptDes(SecurityUtil.java:134) ~[ibase4j-common-3.0.3.jar:?]
	at top.ibase4j.core.config.Configs.postProcessEnvironment(Configs.java:53) ~[ibase4j-common-3.0.3.jar:?]
	at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEnvironmentPreparedEvent(ConfigFileApplicationListener.java:183) ~[spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEvent(ConfigFileApplicationListener.java:169) ~[spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-5.0.2.RELEASE.jar:5.0.2.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-5.0.2.RELEASE.jar:5.0.2.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-5.0.2.RELEASE.jar:5.0.2.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127) ~[spring-context-5.0.2.RELEASE.jar:5.0.2.RELEASE]
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:74) ~[spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54) ~[spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:351) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:317) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1246) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1234) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.ibase4j.SysServiceApplication.main(SysServiceApplication.java:15) [classes/:?]
Caused by: javax.crypto.BadPaddingException: Given final block not properly padded
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:991) ~[sunjce_provider.jar:1.8.0_162]
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:847) ~[sunjce_provider.jar:1.8.0_162]
	at com.sun.crypto.provider.DESCipher.engineDoFinal(DESCipher.java:314) ~[sunjce_provider.jar:1.8.0_162]
	at javax.crypto.Cipher.doFinal(Cipher.java:2164) ~[?:1.8.0_171]
	at top.ibase4j.core.support.security.coder.DESCoder.decrypt(DESCoder.java:86) ~[ibase4j-common-3.0.3.jar:?]
	at top.ibase4j.core.util.SecurityUtil.decryptDes(SecurityUtil.java:132) ~[ibase4j-common-3.0.3.jar:?]
	... 14 more

上面异常信息里显示的这些jar我都检查了，maven已经正常引入

我唯一改过的地方就是refer目录下的两个xml里面的声明版本改成了5.0，原来的4.0会有红叉错误：
<beans xmlns="http://www.springframework.org/schema/beans"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:context="http://www.springframework.org/schema/context"
	xmlns:dubbo="http://code.alibabatech.com/schema/dubbo"
	xsi:schemaLocation="http://www.springframework.org/schema/beans
         http://www.springframework.org/schema/beans/spring-beans-5.0.xsd  
         http://www.springframework.org/schema/context
         http://www.springframework.org/schema/context/spring-context-5.0.xsd
		http://code.alibabatech.com/schema/dubbo
		http://code.alibabatech.com/schema/dubbo/dubbo.xsd">

其他数据库账号、密码(加密)、nginx/zookeeper/redis/activemq都启动了

**Comment by cavancao** [comment]
我Java Application运行的是iBase4J-SYS-Service下面的org.ibase4j.SysServiceApplication

**Comment by wqxcloud** [comment]
我的导入eclipse报错？？？ 怎么弄，很多包报错，按maven导入的
